<?php
// config.php — Auto-generated by docker-entrypoint or install wizard
// Do NOT commit this file to version control.

return [
    'app' => [
        'name' => getenv('APP_NAME') ?: 'xAI CMS',
        'url' => getenv('APP_URL') ?: 'http://localhost:8080',
        'debug' => getenv('APP_DEBUG') === 'true',
        'timezone' => getenv('APP_TIMEZONE') ?: 'Asia/Shanghai',
    ],
    'db' => [
        'host' => getenv('DB_HOST') ?: 'localhost',
        'port' => getenv('DB_PORT') ?: '3306',
        'database' => getenv('DB_DATABASE') ?: 'xaicms',
        'username' => getenv('DB_USERNAME') ?: 'root',
        'password' => getenv('DB_PASSWORD') ?: '',
        'charset' => 'utf8mb4',
    ],
    'ai' => [
        'default_provider' => getenv('AI_PROVIDER') ?: 'deepseek',
        'default_api_key' => getenv('AI_API_KEY') ?: '',
        'default_base_url' => getenv('AI_BASE_URL') ?: 'https://api.deepseek.com/v1',
        'default_model' => getenv('AI_MODEL') ?: 'deepseek-v4-flash',
        'pro_model' => getenv('AI_PRO_MODEL') ?: 'deepseek-v4-pro',
    ],
    'language' => getenv('SITE_LANGUAGE') ?: 'zh-CN',
    'admin_language' => getenv('ADMIN_LANGUAGE') ?: 'zh-CN',
];
